export const GET_ALL_CATEGORIES_START = 'GET_ALL_CATEGORIES_START';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';

export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

export const DELETE_MANY_CATEGORIES_START = 'DELETE_MANY_CATEGORIES_START';
export const DELETE_MANY_CATEGORIES_SUCCESS = 'DELETE_MANY_CATEGORIES_SUCCESS';
export const DELETE_MANY_CATEGORIES_FAILED = 'DELETE_MANY_CATEGORIES_FAILED';

export const DELETE_ALL_CATEGORIES_START = 'DELETE_ALL_CATEGORIES_START';
export const DELETE_ALL_CATEGORIES_SUCCESS = 'DELETE_ALL_CATEGORIES_SUCCESS';
export const DELETE_ALL_CATEGORIES_FAILED = 'DELETE_ALL_CATEGORIES_FAILED';

