export const GET_ALL_ORDERS_START = 'GET_ALL_ORDERS_START';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILED = 'GET_ALL_ORDERS_FAILED';

export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILED = 'UPDATE_ORDER_FAILED';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';

export const DELETE_MANY_ORDERS_START = 'DELETE_MANY_ORDERS_START';
export const DELETE_MANY_ORDERS_SUCCESS = 'DELETE_MANY_ORDERS_SUCCESS';
export const DELETE_MANY_ORDERS_FAILED = 'DELETE_MANY_ORDERS_FAILED';

export const DELETE_ALL_ORDERS_START = 'DELETE_ALL_ORDERS_START';
export const DELETE_ALL_ORDERS_SUCCESS = 'DELETE_ALL_ORDERS_SUCCESS';
export const DELETE_ALL_ORDERS_FAILED = 'DELETE_ALL_ORDERS_FAILED';
