export const GET_ALL_PRODUCTS_START = 'GET_ALL_PRODUCTS_START';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_PRODUCTS_FAILED';

export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const DELETE_MANY_PRODUCTS_START = 'DELETE_MANY_PRODUCTS_START';
export const DELETE_MANY_PRODUCTS_SUCCESS = 'DELETE_MANY_PRODUCTS_SUCCESS';
export const DELETE_MANY_PRODUCTS_FAILED = 'DELETE_MANY_PRODUCTS_FAILED';

export const DELETE_ALL_PRODUCTS_START = 'DELETE_ALL_PRODUCTS_START';
export const DELETE_ALL_PRODUCTS_SUCCESS = 'DELETE_ALL_PRODUCTS_SUCCESS';
export const DELETE_ALL_PRODUCTS_FAILED = 'DELETE_ALL_PRODUCTS_FAILED';


